version: '3.7'
services:
  fednewspush_db:
    image: mongo:latest
    restart: always
    volumes:
      - ~/data/db:/data/db
    network_mode: host
    networks:
      - fednewspush-network
    ports:
      - 27017:27017
  fednewspush_api:
    build: ./
    # image: jzone1985/fednewspush-server
    ports:
      - 7001:7001
    restart: always
    depends_on:
      - fednewspush_db
    network_mode: host
    networks:
      - fednewspush-network
networks:
  fednewspush-network:
    driver: bridge